language: python
python:
  - "2.7"
services:
  - redis-server
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
branches:
  only:
    - travis