language: python
python:
  - "2.7"
before_script: sudo redis-server /etc/redis/redis.conf --port 6379
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
branches:
  only:
    - travis